maintainer = "Chakrit Wichian <chakrit@prodigy9.co>"

excludes = [".git", "node_modules", "*.docker"]
source_url = "https://github.com/prod9/platform"
target_platform = "linux/amd64"

[modules.platform]
binary = "platform"
builder = "go/basic"
image = "ghcr.io/prod9/platform"
package = "platform.prodigy9.co"
wd = "."
