maintainer = "Chakrit Wichian <chakrit@prodigy9.co>"
source_url = "https://github.com/prod9/platform"
target_platform = "linux/amd64"

excludes = [
	"*.docker",
	".git",
	".github",
	".gitignore",
	"node_modules",
	"platform.toml",
]

[modules.platform]
binary = "platform"
builder = "go/basic"
image = "ghcr.io/prod9/platform"
package = "platform.prodigy9.co"
timeout = "10m"
wd = "."
