maintainer = "Chakrit Wichian <chakrit@prodigy9.co>"

environments = ["platform.prodigy9.co"]
platform = "linux/amd64"
repository = "https://github.com/prod9/platform"
strategy = "semver"

excludes = [
	"*.docker",
	"*.local",
	".dockerignore",
	".git",
	".github",
	".gitignore",
	".idea",
	".svelte-kit",
	".vscode",
	"build",
	"dist",
	"node_modules",
	"platform.toml",
	"target",
]

[modules.platform]
builder = "go/basic"
cmd = "platform"
image = "ghcr.io/prod9/platform"
package = "platform.prodigy9.co"
timeout = 60000000000
