maintainer = "Johnny Appleseed <john@apple.com>"
platform = "auto"
repository = "github.com/prod9/platform"
strategy = "timestamp"
excludes = ["*.docker", "*.local", ".dockerignore", ".git", ".github", ".gitignore", ".idea", ".vscode", "node_modules", "platform.toml"]

[modules]
  [modules.pnpmbasic]
    workdir = "."
    timeout = "1m0s"
    builder = "pnpm/basic"
    publish = false
    cmd = "pnpmbasic"
