maintainer = "Johnny Appleseed <john@apple.com>"
platform = "auto"
repository = "github.com/prod9/platform"
strategy = "timestamp"
excludes = ["*.docker", "*.local", ".dockerignore", ".git", ".github", ".gitignore", ".idea", ".vscode", "node_modules", "platform.toml"]

[modules]
  [modules.storybook]
    workdir = "./storybook"
    timeout = "1m0s"
    builder = "pnpm/workspace"
    publish = false
  [modules.web]
    workdir = "./web"
    timeout = "1m0s"
    builder = "pnpm/workspace"
    publish = false
