maintainer = "Johnny Appleseed <john@apple.com>"
platform = "linux/amd64"
repository = "github.com/prod9/platform"
strategy = "timestamp"
excludes = ["*.docker", "*.local", ".dockerignore", ".git", ".github", ".gitignore", ".idea", ".vscode", "node_modules", "platform.toml"]

[modules]
  [modules.gobasic]
    workdir = "./gobasic"
    timeout = 5000000000
    builder = "go/basic"
    publish = false
