maintainer = "Johnny Appleseed <john@apple.com>"
platform = "auto"
repository = "github.com/prod9/platform"
strategy = "timestamp"
excludes = ["*.docker", "*.local", ".dockerignore", ".git", ".github", ".gitignore", ".idea", ".vscode", "node_modules", "platform.toml"]

[modules]
  [modules.app]
    builder = "go/workspace"
    cmd = "app"
    package = "fixtures.platform.prodigy9.co/app"
    publish = false
    timeout = "1m0s"
    workdir = "./app"
  [modules.fx]
    builder = "go/workspace"
    cmd = "fx"
    package = "fixtures.platform.prodigy9.co/fx"
    publish = false
    timeout = "1m0s"
    workdir = "./fx"
