name: platform

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: self-hosted
    environment:
      ALWAYS_YES: "y"
    steps:
      - name: Logs in GHCR.IO
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.5
      - run: go version
      - name: Build & Deploy
        run: go run platform.prodigy9.co/cmd/platform@latest deploy
