
name: platform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Install Go
        uses: actions/setup-go@v4
        with:
         go-version: 1.20.4
      - run: go version
      - name: Build
        run: go run platform.prodigy9.co@latest build
